config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :offers do
    resources :reservations, only: %i[new create]
  end
  resources :reservations, only: %i[index destroy edit update] do
    member do
      patch :accept, to: "reservations#accept", as: :accept
      patch :reject, to: "reservations#reject", as: :reject
    end
  end

  root to: "pages#home"
  get "profil", to: "pages#profil"
  get "profil/:id", to: "pages#profilshow", as: :show_profil

  resources :users, only: %i[edit update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :user
  has_many :reservations, dependent: :destroy
  # Uniqueness: to be tested
  validates :title, presence: true, uniqueness: true, length: { maximum: 30 }
  validates :description, presence: true
  validates :date, presence: true
  validates :price, presence: true
  has_one_attached :photo
end

app/models/reservation.rb
#  To be checked: One user cannot book his own offer
# class UserValidator < ActiveModel::Validator

  #   def validate(record)
#     if record.user == record.offer.user
#       record.errors.add :base, "Cannot book your own offer!"
#     end
#   end
# end

class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :offer
  # Comments: blank at the moment, to be tested
  # To be tested: A user can only book the same offer one time (one more time?!?)
  validates :user, uniqueness: { scope: :offer }
  # validates_with UserValidator // see above
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :offers
  has_many :reservations
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname])
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :owner, only: %i[edit update destroy]
  before_action :set_offer, only: %i[show edit update destroy]

  def index
    if params[:show_owned]
      @offers = current_user.offers
    elsif params[:query].present?
      sql_query = "title ILIKE :query OR description ILIKE :query"
      @offers = Offer.where(sql_query, query: "%#{params[:query]}%")
    else
      @offers = Offer.all
    end
  end

  def show
    @offer = Offer.find(params[:id])
    @reservations = @offer.reservations
    @reserved = false
    @reservations.each do |reservation|
      @reserved = true if reservation.user == current_user
    end
  end

  def new
    @offer = Offer.new
  end

  def create
    # Need to use "current_user.offers.build to assign the user_id to the offer"
    @offer = current_user.offers.build(offer_params)
    if @offer.save
      redirect_to offer_path(@offer)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @offer.update(offer_params)
      redirect_to offer_path(@offer)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @offer.destroy
    redirect_to offers_path(show_owned: true)
  end

  private

  def set_offer
    @offer = Offer.find(params[:id])
  end

  def offer_params
    params.require(:offer).permit(:title, :description, :date, :price, :photo)
  end

  def owner
    @offer = Offer.find(params[:id])
    return if @offer.user == current_user

    flash[:warning] = 'You are not authorized to edit/delete this offer (not the owner).'
    redirect_to offers_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @offers = Offer.order(:date).limit(3)
  end

  def profil
    @user = current_user
    @offers_count = Offer.where(user: current_user).count
    @reservations_count = Reservation.where(user: current_user).count
  end

  def profilshow
    @user = User.find(params[:id])
    @offers_count = Offer.where(user: @user).count
    @reservations_count = Reservation.where(user: @user).count
    render :profil
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_offer, only: %i[new create]

  def index
    @reservations = Reservation.where(user: current_user)
  end

  def new
    @reservation = Reservation.new
  end

  def create
    @reservation = Reservation.new(reservation_params)
    @reservation.offer = @offer
    @reservation.user = current_user
    if @reservation.save
      redirect_to reservations_path
    else
      render "offers/show", status: :unprocessable_entity
    end
  end

  def edit
    @reservation = Reservation.find(params[:id])
  end

  def accept
    @reservation = Reservation.find(params[:id])
    @reservation.accepted = true
    if @reservation.save!
      redirect_to offer_path(@reservation.offer)
    else
      render "offers#show", status: :unprocessable_entity
    end
  end

  def reject
    @reservation = Reservation.find(params[:id])
    @reservation.accepted = false
    if @reservation.save!
      redirect_to offer_path(@reservation.offer)
    else
      render "offers#show", status: :unprocessable_entity
    end
  end

  def update
    @reservation = Reservation.find(params[:id])
    @reservation.accepted = true
    if @reservation.save!
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    redirect_to reservations_path, status: :see_other
  end

  private

  def set_offer
    @offer = Offer.find(params[:offer_id])
  end

  def reservation_params
    params.require(:reservation).permit(:comment, :accepted)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to profil_path(@user)
    else
      render :update, status: :unprocessable_entity
    end
  end
end

private

def user_params
  params.require(:user).permit(:nickname, :email, :description, :photo)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentalFame</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <div class="bodycontent">
      <%= yield %>
    </div>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render "shared/footer" %>
  </body>
</html>

<script src="https://kit.fontawesome.com/ef1288b809.js" crossorigin="anonymous"></script>

app/views/offers/edit.html.erb
<%= render "shared/form", review: @review %>

app/views/offers/index.html.erb
<div class="offers-index">
  <% if @offers.present? %>
    <% @offers.each do |offer| %>
      <%= link_to offer_path(offer.id), class: "offer-index" do %>
        <% if offer.photo.key.present? %>
          <%= cl_image_tag offer.photo.key, class: "photo-index" %>
        <% else %>
          <%= image_tag "Star.png", alt: "No Star", class: "photo-index" %>
        <% end %>
        <h1><%= offer.title %></h1>
        <div class="offer-price-index">$<%= offer.price %></div>
      <% end %>
    <% end %>
  <% else %>
    <p class="response">You have not yet created offers</p>
  <% end %>
</div>

app/views/offers/new.html.erb
<%= render "shared/form", review: @review %>

app/views/offers/show.html.erb
<div class="offer-wrap">

  <div class="offer">
    <div class="text">
      <h1><%= @offer.title %></h1>
      <div class="offer_desc">
        <%= @offer.description %>
      </div>
      <div class="cta">
        <% if current_user == @offer.user %>
          <%= link_to "", edit_offer_path(@offer), class: "fa-solid fa-pencil fa-lg" %>
          <%= link_to "", offer_path(@offer), class: "fa-solid fa-trash-can fa-lg", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
        <% else %>

        <% end %>
      </div>
    </div>

    <div class="offer-image-wrap">
    <% if @offer.photo.key.present? %>
      <%= cl_image_tag @offer.photo.key, class: "photo" %>
    <% else %>
      <%= image_tag "Star.png", alt: "No Star", class: "photo" %>
    <% end %>
      <div class="info-wrap">
        <div class="info">
          <div class="date-block">
            <h2>Available on</h2>
            <div class="offer_date">
              <%= @offer.date.day %>/<%= @offer.date.month %>/<%= @offer.date.year %>
            </div>
          </div>
          <div class="price-block">
            $<%= @offer.price %>
          </div>
        </div>
      </div>
      <div class="border-bottom">
      </div>
    </div>
    <div class="border-right">
    </div>
  </div>

  <div class="resas">
    <% if current_user == @offer.user %>
      <h2>Reservations</h2>
      <% if @offer.reservations.size == 0 %>
        <p>There is no reservation for this offer yet.</p>
      <% else %>
        <div class="resa-wrap">
        <% @offer.reservations.each do |reservation| %>
            <div class="resa">
              <h1><%= link_to reservation.user.nickname, show_profil_path(reservation.user) %></h1>
              <div class="comment">
                <span class="quote">“</span>
                <p><%= reservation.comment %></p>

              </div>
              <div class="btns">
                <% if reservation.accepted %>
                  <p class="accepted"><i class="fa-solid fa-circle-check"></i>Reservation accepted!</p>
                <% else %>
                  <%= link_to "Accept this reservation!", accept_reservation_path(reservation), data: { turbo_method: :patch }, class: "btn_form" %>
                <% end %>
                <%= link_to "Decline", reject_reservation_path(reservation), data: { turbo_method: :patch }, class: "btn_form secondary" %>
              </div>
          </div>
        <% end %>
        </div>
      <% end %>
    <% else %>
      <% if @reserved %>
        <strong><p>You have already made a reservation for this offer!</p></strong>
      <% else %>
        <div>
          <%= render "shared/resaform", reservation: @reservation %>
        </div>
      <% end %>
    <% end %>
  </div>

</div>

app/views/pages/home.html.erb
<div class="homepage-container">

  <div class="banner">
    <%= image_tag "celeb.webp", alt: "Banner Image" %>
  </div>

  <div id="typed-container">
    <div class="banner-ttl"> What are you doing this weekend? </div>
    <span class="sentences" data-controller="typed"
    data-typed-sentences-value="<%= ["Maybe... A baseball with Paul Goldschmidt?", "Maybe.. A dinner with Leonardo DiCaprio?",
    "Maybe.. A cooking class with Gordon Ramsay?", "Maybe.. Organise a golf tournament with Tiger Woods?", "Maybe.. Learn graffiti art in a workshop with Banksy?",
    "Maybe.. A yoga retreat with Gwyneth Paltrow?", "Maybe.. A private concert with Adele?","Maybe.. A surfing expedition with Kelly Slater?",
    "Maybe.. An exclusive film screening with Steven Spielberg?", "Maybe.. A wine tasting with Robert Mondavi Jr?"].to_json %>">
    </span>
  </div>

  <div class="browse-offers">
    <%= link_to "Discover our offers", offers_path, class: "add" %>
    <div class="msg-promo"><i class="fa-solid fa-caret-down fa-sm"></i> Our upcoming offers <i class="fa-solid fa-caret-down fa-sm"></i></div>
  </div>


<div class="offers-index">
  <% @offers.each do |offer| %>
    <%= link_to offer_path(offer.id), class: "offer-index" do %>
      <% if offer.photo.key.present? %>
        <%= cl_image_tag offer.photo.key, class: "photo-index" %>
      <% else %>
        <%= image_tag "Star.png", alt: "No Star", class: "photo-index" %>
      <% end %>
      <h1><%= offer.title %></h1>
      <div class="offer-price-index">$<%= offer.price %></div>
    <% end %>
  <% end %>
</div>
</div>
</div>

app/views/pages/profil.html.erb
<div class="profile">
  <div class = "profile-picture">
    <% if @user.photo.key.present? %>
      <%= cl_image_tag @user.photo.key, class: "photo" %>
    <% else %>
      <%= image_tag "Star.png", alt: "No Star", class: "photo" %>
    <% end %>
  </div>
  <div class="profile-info">
    <h1><%= @user.nickname %></h1>
    <p><%= @user.email %></p>
    <p><%= @user.description %></p>
    <p class="history">
      <% @offers_count > 1 ? offers = "offers" : offers = "offer" %>
      <% @reservations_count > 1 ? resas = "reservations" : resas = "reservation" %>
      <% @user == current_user ? have = "have" : have = "has" %>
      <%= @user == current_user ? "You #{ have }" : "#{ @user.nickname } #{ have }"%>
        created <%= @offers_count %> <%= offers %> and <%= have %> <%= @reservations_count %> <%= resas %>.
      </p>
  </div>
  <% if @user == current_user %>
    <%= link_to "Edit profile", edit_user_path(current_user), class: "edit" %>
    <% end %>
</div>

app/views/reservations/edit.html.erb
<h1><%= @reservation.offer.title%></h1>

<p><%= @reservation.comment %></p>

<%= simple_form_for [@offer, @reservation]  do |f| %>
  <div class="text_form">
    <%= f.input :accepted %>
  </div>
  <%= f.submit class: "btn_form" %>
<% end %>

app/views/reservations/index.html.erb
<div class="global-container">
  <% if @reservations.present? %>
    <% @reservations.each do |reservation| %>
      <% if !reservation.accepted? %>
        <div class="resa-card">
      <% else %>
        <div class="resa-card resa-accept">
      <% end %>
          <% if reservation.offer.photo.key.present? %>
            <%= cl_image_tag reservation.offer.photo.key, class: "photo-form" %>
          <% else %>
            <%= image_tag "Star.png", alt: "No Star", class: "photo-form" %>
          <% end %>
          <div class="resa-info">
            <h1><%= reservation.offer.title %></h1>
            <div class="resa-price-date">
              <span class="resa-price">$<%= reservation.offer.price %></span>
              <span class="resa-date">
                <%= reservation.offer.date.day %>/<%= reservation.offer.date.month %>/<%= reservation.offer.date.year %>
              </span>
            </div>
            <div class="resa-comment">
              <%= reservation.comment %>
            </div>
            <div class="footer_reservation">
              <% if reservation.accepted? %>
                <p class="footer_accepted">Accepted!</p>
              <% else %>
                <p class="footer_status">Pending</p>
                <%= link_to "Cancel reservation", reservation_path(reservation),
                data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"add" %>
              <% end %>
            </div>
          </div>
      </div>
    <% end %>
  <% else %>
    <p class="response">You have no reservations yet</p>
  <% end %>
</div>

app/views/reservations/new.html.erb
<h1>New reservations</h1>
<%= simple_form_for [@offer, @reservation]  do |f| %>
  <div class="text_form">
    <%= f.input :comment %>
  </div>
  <%= f.submit class: "btn_form" %>
<% end %>

<%= link_to "return to the home-pages", root_path %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>
<% if flash[:warning] %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= flash[:warning] %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <%= link_to "Rental Fame", root_path %><i class="fa-regular fa-registered"></i> All rights reserved - <i class="fa-solid fa-crown crown"></i>Made by the RFCompany
</div>

app/views/shared/_form.html.erb
<div class="new-offer-wrap">
  <h1>Let's create an amazing offer!</h1>
  <%= simple_form_for @offer do |f| %>
    <div class="text_form"><%= f.input :title %></div>
    <div class="text_form"><%= f.input :description %></div>
    <div class="date-price">
      <%= f.input :date,
                as: :string,
                input_html: { data: { controller: "datepicker" } } %>
      <%= f.input :price %>
    </div>
    <div class="text_form btn_photo">
      <%= f.input :photo, as: :file %>
    </div>
    <div class="submit-wrap">
      <%= f.submit class: "btn_form" %>
    </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-container">
  <div class="navbar-display">
    <%= link_to offers_path do %>
      <%= image_tag image_path("logo_v2.png"), class: "logo" %>
    <% end %>

    <% if user_signed_in? %>
      <div class="nav-items">
        <%= link_to new_offer_path(@offer), class: "nav-button new" do %>
        <i class="fa-solid fa-plus"></i> New offer
        <% end %>
        <form action="<%= offers_path %>" method="get", class="magic-search">
          <div class="search-input-container">
            <%= text_field_tag :query,
              params[:query],
              class: "magic-search-input",
              placeholder: " Find your fame!"
            %>
            <%= image_submit_tag "magnifying_glass.png", alt: "magnifying glass", class: "search-btn" %>
          </div>
        </form>
        <%= link_to "My offers", offers_path(show_owned: true), class: "nav-button off" %>
        <%= link_to "My reservations", reservations_path, class: "nav-button resa" %>
      <div class="avatar">
      <% if current_user.photo.present? %>
        <%= link_to profil_path do %>
          <%= cl_image_tag current_user.photo.key, class: "avatar" %>
        <% end %>
      <% else %>
        <%= link_to profil_path do %>
        <%= image_tag "Star.png", alt: "Default Avatar", class: "avatar" %>
        <% end %>
      <% end %>
      </div>
        <%= link_to destroy_user_session_path, data: {turbo_method: :delete}, class: "logout-btn" do %>
        <i class="fa-solid fa-xmark"></i> Logout
        <% end %>
      </div>
    <% else %>
      <div class="nav-items">
        <%= link_to "Login", new_user_session_path, class: "nav-button" %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_resaform.html.erb
<% reservation ||= Reservation.new %>

<div class="new-resa">
  <%= form_with(model: [@offer, reservation]) do |f| %>
    <%= f.text_area :comment, placeholder: "Your comment...", class: "text-input" %>
    <%= f.submit value: "Make a reservation!", class: "btn_form submit" %>
  <% end %>
</div>

app/views/shared/_search.html.erb
<div class="magic_search">
  <%= form_with url: offers_path, method: :get, class: "magic_search-form" do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Find your fame!"
    %>
    <%= submit_tag "Search", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="profile-edit">
  <%= simple_form_for (@user)  do |f| %>
    <div>
      <div class="text_form"><%= f.input :nickname %></div>
    </div>
    <div class="form-inputs">
    <%= f.input :email, required: true, autofocus: true %>
    </div>
    <div class="text_form">
      <%= f.input :description %>
    </div>
    <div class="text_form btn_photo">
      <%= f.input :photo, as: :file %>
    </div>
    <%= f.submit class: "btn_form" %>
  <% end %>
</div>